### ISSUE TITLE
Why the rotation cache smoothing from LookMouse?

### ISSUE THREAD

**Issue by namrog84** [ibrahim-syah/FPSCore#44]
Why do you smooth/cache the last 3 frames of rotation and smooth it out in the MyHeroComponent?

e.g. RotArrayX and RotCacheIndex

Just trying to understand/learn.

**Comment by ibrahim-syah** [comment]
It's from this video: https://youtu.be/CmEyXX-7EAc?t=203

Allegedly it's supposed to smooth out the mouse input? I honestly couldn't feel the difference, but yeah I forgot it was there maybe I will revert that.
